apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue-deployment
  labels:
    app: myapp-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp-blue
  template:
    metadata:
      labels:
        app: myapp-blue
    spec:
      containers:
        - name: myapp-nginx
          image: ebinvarghese/myapp-blue:latest
          ports:
            - containerPort: 80