apiVersion: v1
kind: Service
metadata:
  name: myapp-blue-service
  labels:
    app: myapp-blue
spec:
  type: NodePort
  selector:
    app: myapp-blue
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 80
